# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Wheel-UDP
version:      0.01
version_from: lib/POE/Wheel/UDP.pm
installdirs:  site
requires:
    Carp:                          0
    Fcntl:                         0
    POE:                           0
    Socket:                        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
